params:
  use_best_model: False # использовать для тренировки лучшую модель или перебирать все
  iterate_all_params: True # перебирать ли все версии гиперпараметров
  random_state: 42
  path_to_data: None
  target_column_name: "Survived"
  use_all_dataframes: True # использовать ли все версии датафреймов при трейне
  use_dataframe: None # при None выбирается по умолчанию
