models:

  logistic_regression:
    versions:

      baseline:
        max_iter: 1000

      l2:
        penalty: l2
        C: 0.1
        max_iter: 100
        solver: lbfgs

      l1:
        penalty: l1
        C: 1.0
        solver: saga
        max_iter: 1000

      elasticnet:
        penalty: elasticnet
        C: 1.0
        l1_ratio: 0.5
        solver: saga
        max_iter: 1000

  knn:
    versions:

      default:
        n_neighbors: 5
        weights: uniform
        algorithm: auto

  decision_tree:
    versions:
      default:
        max_depth: 5
        min_samples_split: 2
        min_samples_leaf: 1
        random_state: 42

  random_forest:
    versions:
      best:
        n_estimators: 350
        max_depth: 7
        max_samples: 0.9
        min_samples_split: 2
        max_features: 7
        random_state: 42
        n_jobs: -1

  catboost:
    versions:
      default:
        iterations: 250
        learning_rate: 0.073
        depth: 3
        l2_leaf_reg: 5

  xgboost:
    versions:
      best:
        n_estimators: 300
        max_depth: 6
        learning_rate: 0.05
        subsample: 0.9
        colsample_bytree: 0.9
        random_state: 42
        n_jobs: -1

  lightgbm:
    versions:
      default:
        num_leaves: 5
        min_data_in_leaf: 25
        learning_rate: 0.04
        n_estimators: 250
        n_jobs: -1

  stacking:
    versions:
      default:
        base_models:
          knn:
            n_neighbors: 10
          svc:
            probability: true
          tree:
            max_depth: 5
            random_state: 42
            min_samples_leaf: 5
        meta_model: logistic_regression
        cv: 5

  voting:
    versions:
      default:
        estimators:
          - logistic_regression
          - knn
          - svc
        voting: soft